language: node_js
node_js:
  - "stable"

branches:
  only:
    - master
    - staging

addons:
  ssh_known_hosts: nl1-ts1.a2hosting.com

cache:
  directories:
    - node_modules

script:
  - npm test
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_<...>_key -iv $encrypted_<...>_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build getcoac1@nl1-ts1.a2hosting.com:/home/getcoac1/coachified.xyz
    on:
      branch: staging
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/build getcoac1@nl1-ts1.a2hosting.com:/home/getcoac1/coachified.app
    on:
      branch: master
